import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Navbar } from "./components";  
import { Footer } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce app",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout">
          <Head>
            <title>Pacific Store</title>
          </Head>
          <header>
            <Navbar />
          </header>

          <main className="main-container">{children}</main>

          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
